### ISSUE TITLE
Timeout when downloading openapi 

### ISSUE THREAD

**Issue by weidi** [benclaussen/NetboxPS#13]
Hi,

the Timeout for downloading the openapi is set to 5 seconds, my instance takes about 11 seconds.
That means on connect it times out but when changing the timeout values to 15 sec it works fine.
Do you know why this may take that long? Also i would suggest changing the hardcoded timeout value to 30 seconds.

BR
Johannes

**Comment by alagoutte** [comment]
Hi Johannes,

it is funny, i get the same issue...

The timeout is 10 secs for openapi

it is "longer" because need to download all openapi schema...

but actually, the code only search the version of netbox, i think replace by check status uri (where there is the version too) (i waiting merge of #12 for push a another change)

**Comment by weidi** [comment]
Sounds great, sorry wasn´t looking at the mergerequest but for sure it makes more sense to get the version from status uri.

**Comment by alagoutte** [comment]
i think, kept open, it is not yet fixed ;-)

**Comment by benclaussen** [comment]
> 
> 
> Hi Johannes,
> 
> it is funny, i get the same issue...
> 
> The timeout is 10 secs for openapi
> 
> it is "longer" because need to download all openapi schema...
> 
> but actually, the code only search the version of netbox, i think replace by check status uri (where there is the version too) (i waiting merge of #12 for push a another change)

The idea behind downloading the whole API definition was for parameter validation later, such as Status, Role, etc. Never got around to it, however.

We can certainly change to check the version only until parameter validation logic is written.

**Comment by alagoutte** [comment]
Yes, i understand the idea too ;) but yes it is not used actually...

**Comment by benclaussen** [comment]
Fixed in #14
