### ISSUE TITLE
PSSA - Do not fail on Informational

### ISSUE THREAD

**Issue by benclaussen** [benclaussen/NetboxPS#15]
@alagoutte 

https://github.com/benclaussen/NetboxPS/blob/2b7c1b4be370df4c01a099b43978a9f9b9f6361f/.github/workflows/pssa.yml#L14

Propose changing to `failOnInfos: false`

These are generally extra whitespace which are not immediate causes for concern.

Thoughts?

**Comment by alagoutte** [comment]
Hi Ben,

yes… or fix trailing White space issue !
