### ISSUE TITLE
Support for Assigned_object_type in New-NetboxIPAMAddress

### ISSUE THREAD

**Issue by weidi** [benclaussen/NetboxPS#17]
When creating a new IPAMAddress for a virtual Machine this needs to be split in two sections as New-NetboxIPAMAddress does not support parameter Assigned_Object_Type and Assigned_Object_Id
```
$NBip = New-NetboxIPAMAddress -Address $IP -Tenant $NBtenant.id 
Set-NetboxIPAMAddress -Assigned_Object_Type virtualization.vminterface -Assigned_Object_Id $interface.id -id $NBip.id
```
Optimally this should be one call like 
```
$NBip = New-NetboxIPAMAddress -Address $IP -Tenant $NBtenant.id -Assigned_Object_Type virtualization.vminterface -Assigned_Object_Id $interface.id
```

**Comment by alagoutte** [comment]
Yes !

Confirmed, i will look for add this

**Comment by benclaussen** [comment]
Should be easy enough by simply adding the parameters to the `New-NetboxIPAMAddress` function like they are in `Set-NetboxIPAMAddress`.

**Comment by alagoutte** [comment]
> 
> 
> Should be easy enough by simply adding the parameters to the `New-NetboxIPAMAddress` function like they are in `Set-NetboxIPAMAddress`.

Yes, work in progress with some enhance :)
