### ISSUE TITLE
Remove use of System.Web class for .NET Core

### ISSUE THREAD

**Issue by benclaussen** [benclaussen/NetboxPS#23]
>`System.Web` assembly is not available in .NET Core. This module makes use of it in `Functions\Helpers\BuildNewURI.ps1` to create a URI query string (~Line 80). 
>
>We will need to implement a new function to build this string and properly escape characters without using the `System.Web` class.

_Originally posted by @benclaussen in https://github.com/benclaussen/NetboxPS/issues/2#issuecomment-885905781_

This will permit the use of the Github release action to publish to PSGallery

**Comment by alagoutte** [comment]
the script work... there is the module on PSGallery https://www.powershellgallery.com/packages/NetboxPS/

but yes, we need to found how avoid this error...
