### ISSUE TITLE
Get-NetboxIPAMVLAN fails with error

### ISSUE THREAD

**Issue by pceslayer** [benclaussen/NetboxPS#28]
Get-NetboxIPAMVLAN : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-NetboxIPAMVLAN
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-NetboxIPAMVLAN], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Get-NetboxIPAMVLAN

I was able to fix by setting [CmdletBinding(DefaultParameterSetName = 'Query')]

**Comment by alagoutte** [comment]
Yes, i get the same issue

Yes, i have push the same fix for DCIM(Site) : https://github.com/benclaussen/NetboxPS/pull/25/commits/59e19f361cd069fd8acd51fbc66964ceefd12297

do you think push a fix ? (Vlan need also more enhance like fix some typo, example and add Set and Remove cmdlet)

**Comment by alagoutte** [comment]
i start to work on fix and enhance vlan https://github.com/alagoutte/NetboxPS/tree/vlan i will push on next week (and want to work some test also)
