### ISSUE TITLE
Implement Address Ranges

### ISSUE THREAD

**Issue by weidi** [benclaussen/NetboxPS#31]
Seems that IP Ranges are not supported today but would be greated to see them implemented. Would ease up DHCP Scope automation  or so.

**Comment by weidi** [comment]
Is there an easy way to pull the parameters that the API provides to automatically build the PowerShell parameter set, or are you doing it by hand?

Build the Get-IPAMAddressRange function by hand but thought on a way thats quicker that i´m not aware of

**Comment by alagoutte** [comment]
Hi Weidi,

You need to build by hand... 

i have already try to use autorest but don't work :-( (for autogenerate powershell using openapi netbox spec)

**Comment by benclaussen** [comment]
Added in #50
