### ISSUE TITLE
Implement FHRP Groups

### ISSUE THREAD

**Issue by GitOuttaHereNerd** [benclaussen/NetboxPS#36]
I have these scripts that I made, they aren't perfect at all but they work.

**Comment by GitOuttaHereNerd** [comment]
> I have these scripts that I made, they aren't perfect at all but they work.
[New-NetboxIPAMFHRP-Group-Assignmens.txt](https://github.com/benclaussen/NetboxPS/files/9096876/New-NetboxIPAMFHRP-Group-Assignmens.txt)
[Get-NetboxIPAMFHRP-Group-Assignments.txt](https://github.com/benclaussen/NetboxPS/files/9096877/Get-NetboxIPAMFHRP-Group-Assignments.txt)
[Get-NetboxIPAMFHRP-Groups.txt](https://github.com/benclaussen/NetboxPS/files/9096878/Get-NetboxIPAMFHRP-Groups.txt)
[New-NetboxIPAMFHRP-Groups.txt](https://github.com/benclaussen/NetboxPS/files/9096879/New-NetboxIPAMFHRP-Groups.txt)

**Comment by alagoutte** [comment]
Hi @GitOuttaHereNerd can you a PR with the change ?
